name: Github Actions hello-world #workflow name
run-name: ${{github.actor}} is testing github actions
on: [push]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Hellow-World
        run: echo "Hello Arivasu K"
